### ISSUE TITLE
Give Check-ins Theming Powers

### ISSUE THREAD

**Issue by jackkeller** [objectcomputing/check-ins#2233]
# Acceptance Criteria

As an app, I would like to be able to provide a dark mode for those who've chosen this as their primary color scheme, so that I can be more enjoyable for the masses.

## Tasks

- [ ] Create Global Theme file w/ Light and Dark Scheme variables
- [ ] Integrate into the home page
- [ ] Investigate LOE on updating components
  - ~ 50 css files in the project that may need to be altered
  - the updates could be minimal
- [ ] Consider future story to add a way for users to store their preference for light or dark mode

## Developer Notes

- TBD
