### ISSUE TITLE
Adjustments to volunteer tracking

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2608]
**As a user editing their own profile**, I should be able to simply edit the organizations and events I have been a part of **so that** other team members can see what organizations I have supported.

## Acceptance Criteria

 * [x] The "MY ORGS" and "EVENTS" tabs are visible
 * [x] The current "ORGANIZATIONS" tab is not visible 
 * [x] The message "The administrator may edit organizations to ensure accuracy." appears at the bottom of the table containing relationships with organizations.
 * [x] The Card element that is currently containing only the data table has visually been "pulled up" to contain the tabs as well
 * [x] The Tab titles have been adjusted to include the icons and mimic the styles of the Card titles currently positioned above the data tables
 * [x] The titles currently positioned above the data tables have been removed
 * [x] The Card element and its contents have been adjusted to fill the entire width of the available area similar to the "Skills" card
 * [x] The Card element has been raised above the "Skills" card on the screen.
 * [x] On the "Add Relationship" dialog:
   * [x] Only allow a new relationship with an existing organization if:
     * [x] There is no relationship with this organization already, **OR**
     * [x] Any existing relationships with this organization have an end date
   * [x] The start date must be on or before the current date
   * [x] If an end date is entered it must be after the start date
 * [x] On the "Add Event" dialog:
   * [x] The "Hours" input label has been changed to "Hours You Volunteered"
   * [x] Only show organization relationships that do not have an end date
   * [x] Allow a new organization relationship to be added by selecting "Add a new organization" from the "Organization" input

### Current UI
![Screenshot 2024-09-26 at 11 50 47 AM](https://github.com/user-attachments/assets/dca2c621-4e89-4aaf-8300-89dfe91314f1)

### Desired UI
![desiredui](https://github.com/user-attachments/assets/54372481-b39e-480c-9a37-c64dc3684f57)

**Comment by mkimberlin** [comment]
@thelenw I did a quick review of this issue and it looks like there are some acceptance criteria that still need to be addressed. Perhaps you could pick this one back up and wrap those last few adjustments?

**Comment by thelenw** [comment]
On it

**Comment by thelenw** [comment]
Complete. See #2623
