### ISSUE TITLE
Adjustments to certification tracking

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2609]
**As a user editing their own profile***, I want to quickly and easily manage my certifications, **so that** the company and my co-workers know what I am professionally certified for.

## Acceptance Criteria

 - [ ] The Earned Certifications card and its contents should utilize the entire available width, much like the "Skills" card
 - [ ] The Earned Certifications card should appear before the "Skills" card and after the volunteer organization/events card
 - [ ] When adding an Earned Certification:
   - [ ] The description field should not be available, this is incorrectly associated with the earned certification entity and should instead be a part of the certification entity.
   - [ ] The image URL input and its associated data field should be adjusted to "Validation URL" and `validationUrl`, respectively.
 - [ ] When adding a Certification (type), the Badge URL should not be required (may require service/database changes)
 - [ ] ***Note:*** Though this includes potentially destructive changes to the certification and earned certification tables, neither has been deployed to a production environment. So, we can make the change without converting the data. To ensure successful deployment in `DEV`, I would advise adding `delete` statements to the test data load script.
